name: 上傳照片（自動編號）
description: 用手機或電腦都可。選照片後，把每張圖片中括號內的文字改成要顯示的標題即可。
title: "照片上傳："
labels: [auto-upload]
body:
  - type: markdown
    attributes:
      value: |
        **使用方式（手機／電腦皆可）：**
        1. 點下方「照片與標題」大白框 → 點白框底下的**灰字**「Paste, drop, or click to add files」，或工具列的**圖片/相機**圖示。
           - iPhone：會跳出「拍照或錄影 / 照片圖庫 / 瀏覽」。
           - Android：會跳出「相機 / 相簿 / 檔案」。
        2. 選好後，白框內會出現一行行的內容，例如：  
           `![image](https://…/你的圖片連結)`
        3. **把 `![image]` 裡面的 `image` 改成要顯示的標題**（每張都可改），例如：  
           `![第一天報到](https://…/xxx.png)`
        4. 送出後，機器人會**自動編號**、把照片放進 `photos/`，並更新相簿。

  - type: textarea
    id: images
    attributes:
      label: 照片與標題
      description: |
        一次可多張。請把每行 `![image]` 的 `image` 改成你想顯示的標題。
        支援：jpg / jpeg / png / webp。建議單張 < 3MB。
      placeholder: 點這裡，上傳照片…
      value: |
        範例（把中括號改成你的標題；用完可刪這行）：
        ![第一天報到](https://user-images.githubusercontent.com/xxxx/your-image.png)
    validations:
      required: true
