name: 上傳照片（自動編號）
description: 把照片拖到下方「照片與標題」欄位；每張照片的方括號文字就是相簿上要顯示的標題。
title: "照片上傳："
labels: [auto-upload]
body:
  - type: textarea
    id: images
    attributes:
      label: 照片與標題
      description: |
        1) 把照片拖曳到這一格，會自動插入形如 `![image](https://user-images...)` 的一行。
        2) 請把 `![image]` 裡面的 **image** 改成要顯示的標題，例如 `![第一天報到](...)`。
        3) 送出後，機器人會自動編號並更新相簿。
      placeholder: 在這裡拖曳照片…（或貼上）
      value: |
        範例（把中括號改成你的標題）：
        ![第一天報到](https://user-images.githubusercontent.com/xxxxxxx/your-image.png)
    validations:
      required: true
